version: "3"

services:
  postgres_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stoick
      - POSTGRES_PASSWORD=password
    volumes:
      - ./docker/db:/var/lib/postgresql

  app:
    build: .
    volumes:
      - .:/go/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
#     deploy:
#       replicas: 3
#       restart_policy:
#         condition: on-failure
#     networks:
#       - webnet
# networks:
#   webnet: